//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public int IngredientID { get; set; }
        public string IngredientName { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
    }
}
